# Generated by Django 4.0.4 on 2022-05-10 04:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('created_at', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=255)),
                ('company_url', models.URLField()),
                ('location', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('how_to_apply', models.TextField()),
                ('company_logo', models.URLField()),
            ],
        ),
    ]
