# Generated by Django 4.0.4 on 2022-05-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='company_logo',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='created_at',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='how_to_apply',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
